DROP TABLE IF EXISTS pildata;
CREATE TABLE pildata(
  idx int(3) not null auto_increment primary key,
  optGroup varchar(20) not null,
  optData varchar(40)
);

insert into pildata (optGroup,optData) values
('agama','ISLAM'),
('agama','KRISTEN'),
('agama','KATHOLIK'),
('agama','HINDU'),
('agama','BUDHA'),
('agama','KONGHUCU'),
('agama','KEPERCAYAAN'),
('shk','KEPALA KELUARGA'),
('shk','SUAMI'),
('shk','ISTRI'),
('shk','ANAK'),
('shk','MENANTU'),
('shk','CUCU'),
('shk','ORANG TUA'),
('shk','MERTUA'),
('shk','FAMILI LAIN'),
('shk','PEMBANTU'),
('shk','LAINNYA'),
('pdd','TIDAK/BELUM SEKOLAH'),
('pdd','BELUM TAMAT SD/SEDERAJAT'),
('pdd','TAMAT SD/SEDERAJAT'),
('pdd','SLTP/SEDERAJAT'),
('pdd','SLTA/SEDERAJAT'),
('pdd','DIPLOMA I/II'),
('pdd','AKADEMI/DIPLOMA III/SARJANA MUDA'),
('pdd','DIPLOMA IV/STRATA I'),
('pdd','STRATA II'),
('pdd','STRATA III'),
('pkj','BELUM / TIDAK BEKERJA'),
('pkj','MENGURUS RUMAH TANGGA'),
('pkj','PELAJAR/MAHASISWA'),
('pkj','PENSIUNAN'),
('pkj','PEGAWAI NEGERI SIPIL'),
('pkj','TENTARA NASIONAL INDONESIA'),
('pkj','KEPOLISIAN RI'),
('pkj','PERDAGANGAN'),
('pkj','PETANI/PEKEBUN'),
('pkj','PETERNAK'),
('pkj','NELAYAN/PERIKANAN'),
('pkj','INDUSTRI'),
('pkj','KONSTRUKSI'),
('pkj','TRANSPORTASI'),
('pkj','KARYAWAN SWASTA'),
('pkj','KARYAWAN BUMN'),
('pkj','KARYAWAN BUMD'),
('pkj','KARYAWAN HONORER'),
('pkj','UBURUH HARIAN LEPAS'),
('pkj','BURUH TANI/PERKEBUNAN'),
('pkj','BURUH NELAYAN/PERIKANAN'),
('pkj','BURUH PETERNAKAN'),
('pkj','PEMBANTU RUMAH TANGGA'),
('pkj','TUKANG CUKUR'),
('pkj','TUKANG LISTRIK'),
('pkj','TUKAN BATU'),
('pkj','TUKANG KAYU'),
('pkj','TUKANG SOL SEPATU'),
('pkj','TUKANG LAS / PANDE BESI'),
('pkj','TUKANG JAHIT'),
('pkj','TUKANG GIGI'),
('pkj','PENATA RIAS'),
('pkj','PENATA BUSANA'),
('pkj','PENATA RAMBUT'),
('pkj','MEKANIK'),
('pkj','SENIMAN'),
('pkj','TABIB'),
('pkj','PENGRAJIN'),
('pkj','PERANCANG BUSANA'),
('pkj','PENTERJEMAH'),
('pkj','IMAM MASJID'),
('pkj','PENDETA'),
('pkj','PASTOR'),
('pkj','WARTAWAN'),
('pkj','USTADZ/MUBALIGH'),
('pkj','JURU MASAK'),
('pkj','PROMOTOR ACARA'),
('pkj','ANGGOTA DPR'),
('pkj','ANGGOTA DPD'),
('pkj','ANGGOTA BPK'),
('pkj','PRESIDEN'),
('pkj','WAKIL PRESIDEN'),
('pkj','ANGOTA MK'),
('pkj','ANGGOTA KABINET'),
('pkj','DUTA BESAR'),
('pkj','GUBERNUR'),
('pkj','WAKIL GUBERNUR'),
('pkj','BUPATI'),
('pkj','WAKIL BUPATI'),
('pkj','WALIKOTA'),
('pkj','WAKIL WALIKOTA'),
('pkj','ANGGOTA DPRD PROPINSI'),
('pkj','ANGGOTA DORD KABUPATEN'),
('pkj','DOSEN'),
('pkj','GURU'),
('pkj','PILOT'),
('pkj','PENGACARA'),
('pkj','NOTARIS'),
('pkj','ARSITEK'),
('pkj','AKUNTAN'),
('pkj','KONSULTAN'),
('pkj','DOKTER'),
('pkj','BIDAN'),
('pkj','PERAWAT'),
('pkj','APOTEKER'),
('pkj','PSIKIATER/PSIKOLOG'),
('pkj','PENYIAR TELEVISI'),
('pkj','PENYIAR RADIO'),
('pkj','PELAUT'),
('pkj','PENELITI'),
('pkj','SOPIR'),
('pkj','PIALANG'),
('pkj','PARANORMAL'),
('pkj','PEDAGANG'),
('pkj','PERANGKAT DESA'),
('pkj','KEPALA DESA'),
('pkj','BIARAWATI'),
('pkj','WIRASWASTA');
